const express = require('express');
const multer = require('multer');
const Database = require('better-sqlite3');
const pdfParse = require('pdf-parse');
const mammoth = require('mammoth');
const XLSX = require('xlsx');
const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');
const { execFile } = require('child_process');
const { promisify } = require('util');
const { Document, Packer, Paragraph, HeadingLevel, Table, TableRow, TableCell, WidthType } = require('docx');
const execFileAsync = promisify(execFile);

const app = express();
const PORT = process.env.PORT || 3000;
const ROOT = __dirname, DATA = path.join(ROOT,'data'), UPLOADS = path.join(ROOT,'uploads'), REPORTS = path.join(ROOT,'reports');
[DATA,UPLOADS,REPORTS].forEach(d=>fs.mkdirSync(d,{recursive:true}));
const db = new Database(path.join(DATA,'cmine.db')); db.pragma('journal_mode=WAL');
db.exec(`
CREATE TABLE IF NOT EXISTS documents(id INTEGER PRIMARY KEY AUTOINCREMENT,filename TEXT,original_name TEXT,mime TEXT,size INTEGER,sha256 TEXT,status TEXT DEFAULT 'queued',extracted_chars INTEGER DEFAULT 0,pages INTEGER DEFAULT 0,created_at TEXT);
CREATE TABLE IF NOT EXISTS document_text(id INTEGER PRIMARY KEY AUTOINCREMENT,document_id INTEGER,page INTEGER,sheet TEXT,text TEXT NOT NULL,FOREIGN KEY(document_id) REFERENCES documents(id));
CREATE TABLE IF NOT EXISTS facts(id INTEGER PRIMARY KEY AUTOINCREMENT,document_id INTEGER,field TEXT,entity TEXT,period TEXT,value TEXT,unit TEXT,source_page INTEGER,source_sheet TEXT,snippet TEXT,confidence REAL,created_at TEXT,FOREIGN KEY(document_id) REFERENCES documents(id));
CREATE TABLE IF NOT EXISTS conflicts(id INTEGER PRIMARY KEY AUTOINCREMENT,field TEXT,entity TEXT,period TEXT,fact_ids TEXT,details TEXT,status TEXT DEFAULT 'needs_review',created_at TEXT);
`);
const upload=multer({dest:UPLOADS,limits:{files:20,fileSize:50*1024*1024}}); app.use(express.json({limit:'2mb'})); app.use(express.static(path.join(ROOT,'public')));
const now=()=>new Date().toISOString(), clean=s=>String(s??'').replace(/\s+/g,' ').trim();
const sha256=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
async function hasCommand(c){try{await execFileAsync(process.platform==='win32'?'where':'which',[c]);return true}catch{return false}}
async function ocrImage(f){if(!(await hasCommand('tesseract')))return null;try{const {stdout}=await execFileAsync('tesseract',[f,'stdout','--psm','6'],{maxBuffer:20*1024*1024});return clean(stdout)}catch{return null}}
async function ocrPdf(f){if(!(await hasCommand('pdftoppm'))||!(await hasCommand('tesseract')))return[];const t=fs.mkdtempSync(path.join(os.tmpdir(),'cmine-')),p=path.join(t,'page'),out=[];try{await execFileAsync('pdftoppm',['-jpeg','-r','150',f,p],{maxBuffer:20*1024*1024});const imgs=fs.readdirSync(t).filter(x=>x.startsWith('page-')&&x.endsWith('.jpg')).sort();for(let i=0;i<imgs.length;i++){const x=await ocrImage(path.join(t,imgs[i]));if(x)out.push({page:i+1,text:x})}}catch{}fs.rmSync(t,{recursive:true,force:true});return out}
function pdfPages(text){const a=String(text||'').split(/\f/g);return a.map((t,i)=>({page:i+1,text:clean(t)})).filter(x=>x.text)}
async function extractFile(file){const ext=path.extname(file.originalname).toLowerCase();
 if(ext==='.pdf'){const parsed=await pdfParse(fs.readFileSync(file.path));let pages=pdfPages(parsed.text);let mode='pdf-text';if(clean(parsed.text).length<250){const o=await ocrPdf(file.path);if(o.length){pages=o;mode='pdf-ocr'}}return{pages,total:pages.reduce((n,p)=>n+p.text.length,0),mode}}
 if(ext==='.docx'){const r=await mammoth.extractRawText({path:file.path});const t=clean(r.value);return{pages:t?[{page:null,text:t}]:[],total:t.length,mode:'docx'}}
 if(['.xlsx','.xls','.csv'].includes(ext)){const wb=XLSX.readFile(file.path,{cellDates:true});const pages=[];for(const s of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[s],{header:1,raw:false});const t=rows.map(r=>r.map(v=>clean(v)).filter(Boolean).join(' | ')).filter(Boolean).join('\n');if(t)pages.push({page:null,sheet:s,text:t})}return{pages,total:pages.reduce((n,p)=>n+p.text.length,0),mode:'spreadsheet'}}
 if(['.png','.jpg','.jpeg','.webp','.bmp','.tif','.tiff'].includes(ext)){const t=await ocrImage(file.path);return{pages:t?[{page:1,text:t}]:[],total:t?t.length:0,mode:'image-ocr'}}
 const t=clean(fs.readFileSync(file.path,'utf8'));return{pages:t?[{page:1,text:t}]:[],total:t.length,mode:'text'};
}
const RULES=[
 ['production',/(production|output)[^\d]{0,100}([\d,]+(?:\.\d+)?)\s*(mt|million tonnes?|tonnes?|t)?/ig],
 ['dispatch',/(dispatch(?:ed)?|despatch|offtake)[^\d]{0,100}([\d,]+(?:\.\d+)?)\s*(mt|million tonnes?|tonnes?|t)?/ig],
 ['drilling',/(drilling|exploratory drilling)[^\d]{0,100}([\d,]+(?:\.\d+)?)\s*(lakh metres?|million metres?|metres?|m)?/ig],
 ['target',/(target)[^\d]{0,100}([\d,]+(?:\.\d+)?)\s*(mt|million tonnes?|tonnes?|t)?/ig],
 ['reserves',/(reserves?|resources?)[^\d]{0,100}([\d,]+(?:\.\d+)?)\s*(mt|million tonnes?|tonnes?|t)?/ig],
 ['overburden',/(overburden|ob removal)[^\d]{0,100}([\d,]+(?:\.\d+)?)\s*(million m3|m3|cum|cubic metres?)?/ig],
 ['exploration',/(exploration)[^\d]{0,100}([\d,]+(?:\.\d+)?)\s*(lakh metres?|metres?|m|km)?/ig]
];
function entity(t){const m=t.match(/\b([A-Z][A-Za-z&.-]*(?:\s+[A-Z][A-Za-z&.-]*){0,5}\s+(?:Mine|Colliery|Project|Block|Command Area))\b/);return m?clean(m[1]):''}
function period(t){let m=t.match(/\b(20\d{2}\s*[-/]\s*\d{2,4})\b/);if(m)return m[1].replace(/\s+/g,'');m=t.match(/\b(20\d{2})\b/);return m?m[1]:''}
function extractFacts(id,pages){const ins=db.prepare(`INSERT INTO facts(document_id,field,entity,period,value,unit,source_page,source_sheet,snippet,confidence,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`);const tx=db.transaction(()=>{for(const p of pages)for(const [field,re] of RULES){re.lastIndex=0;let m;while((m=re.exec(p.text))){const val=m[2].replace(/,/g,'');const sn=clean(p.text.slice(Math.max(0,m.index-120),Math.min(p.text.length,m.index+m[0].length+180)));ins.run(id,field,entity(p.text),period(p.text),val,clean(m[3]||''),p.page||null,p.sheet||null,sn,0.75,now())}}});tx()}
function rebuildConflicts(){db.prepare('DELETE FROM conflicts').run();const fsx=db.prepare('SELECT * FROM facts WHERE value<>\'\'').all();const g=new Map();for(const f of fsx){const k=[f.field,f.entity||'',f.period||''].join('|');if(!g.has(k))g.set(k,[]);g.get(k).push(f)}const ins=db.prepare('INSERT INTO conflicts(field,entity,period,fact_ids,details,status,created_at) VALUES(?,?,?,?,?,?,?)');for(const a of g.values()){const vals=[...new Set(a.map(x=>`${x.value} ${x.unit||''}`.trim()))];if(vals.length>1)ins.run(a[0].field,a[0].entity||'',a[0].period||'',JSON.stringify(a.map(x=>x.id)),JSON.stringify(a.map(x=>({id:x.id,value:x.value,unit:x.unit,documentId:x.document_id,page:x.source_page,sheet:x.source_sheet,snippet:x.snippet}))), 'needs_review',now())}}
function tokenize(q){return(clean(q).toLowerCase().match(/[a-z0-9]+(?:[-'][a-z0-9]+)*/g)||[])}
function evidence(q){const toks=tokenize(q).filter(x=>x.length>2);if(!toks.length)return[];const rows=db.prepare('SELECT dt.*,d.original_name FROM document_text dt JOIN documents d ON d.id=dt.document_id').all();return rows.map(r=>{const l=r.text.toLowerCase(),hits=toks.reduce((n,t)=>n+(l.includes(t)?1:0),0);if(!hits)return null;const pos=toks.map(t=>l.indexOf(t)).filter(i=>i>=0).sort((a,b)=>a-b)[0]||0;return{...r,score:+(hits/toks.length).toFixed(3),snippet:clean(r.text.slice(Math.max(0,pos-180),pos+520))}}).filter(Boolean).sort((a,b)=>b.score-a.score).slice(0,8)}
function detectIntent(q){const t=tokenize(q);let field=t.find(x=>['production','dispatch','drilling','target','reserves','overburden','exploration'].includes(x));if(!field&&t.some(x=>['output','produced'].includes(x)))field='production';const compare=t.some(x=>['compare','versus','vs','difference','trend','growth','change'].includes(x));const year=t.find(x=>/^20\d{2}$/.test(x));return{field,compare,year,tokens:t}}
function answerFacts(q){const i=detectIntent(q);let rows=db.prepare('SELECT f.*,d.original_name FROM facts f JOIN documents d ON d.id=f.document_id ORDER BY f.id DESC').all();if(i.field)rows=rows.filter(x=>x.field===i.field);if(i.year)rows=rows.filter(x=>(x.period||'').includes(i.year)||x.snippet.includes(i.year));const stop=new Set(['what','was','were','the','from','during','for','show','give','tell','compare','versus','vs','difference','trend','growth','change','production','dispatch','drilling','target','reserves','overburden','exploration','mine','mines','year','between','and','of']);const ents=i.tokens.filter(x=>!stop.has(x)&&x.length>2);if(ents.length)rows=rows.filter(x=>ents.some(t=>(x.entity||'').toLowerCase().includes(t)||(x.snippet||'').toLowerCase().includes(t)||(x.original_name||'').toLowerCase().includes(t)));return rows.slice(0,30)}
function corpusTopics(){const rows=db.prepare('SELECT text FROM document_text').all();const stop=new Set('the and for with from that this are was were have has had into their about which while where when what coal mine mining report annual year production dispatch target project geological geology exploration data table figure million tonnes mt of to in on by as an is be or at it its ministry during total actual estimated'.split(' '));const c=new Map();for(const r of rows){for(const w of (r.text.toLowerCase().match(/[a-z][a-z-]{3,}/g)||[]))if(!stop.has(w))c.set(w,(c.get(w)||0)+1)}const terms=[...c].sort((a,b)=>b[1]-a[1]).slice(0,40).map(([term,count])=>({term,count}));const groups=[['Production & Dispatch',['production','dispatch','supply','offtake','output']],['Geology & Exploration',['geological','geology','exploration','drilling','borehole','resource','reserve']],['Mining Operations',['mining','mine','overburden','excavation','seam','safety']],['Projects & Infrastructure',['project','infrastructure','development','transport','rail','road']]].map(([topic,keys])=>({topic,score:keys.reduce((s,k)=>s+(c.get(k)||0),0),terms:keys.filter(k=>c.has(k))})).sort((a,b)=>b.score-a.score);return{terms,groups}}
function normalize(v,u){let n=Number(v);if(!Number.isFinite(n))return null;u=(u||'').toLowerCase();if(u.includes('lakh'))return n*100000;if(u.includes('million')&&u.includes('ton'))return n*1000000;if(u==='mt'||u.includes('million tonne'))return n*1000000;if(u==='t'||u==='tonnes'||u==='tonne')return n;return n}
async function localOllama(q,context){if(String(process.env.CMINE_AI||'').toLowerCase()!=='ollama')return null;try{const prompt=`You are C-MINE Intelligence. Answer only from the evidence below. If evidence is insufficient, say so. Cite document and page when present.\nQuestion: ${q}\nEvidence:\n${context}`;const r=await fetch('http://127.0.0.1:11434/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:process.env.CMINE_MODEL||'llama3.2:3b',prompt,stream:false})});if(!r.ok)return null;const j=await r.json();return j.response||null}catch{return null}}
app.get('/api/health',(q,r)=>r.json({ok:true,service:'C-Mine Intelligence',problemStatement:'SIH26023',version:'2.0.0',costModel:'local-first / no paid API required'}));
app.get('/api/summary',(q,r)=>{const d=db.prepare(`SELECT COUNT(*) n,SUM(status='processed') processed,COALESCE(SUM(extracted_chars),0) chars FROM documents`).get(),f=db.prepare('SELECT COUNT(*) n FROM facts').get(),c=db.prepare(`SELECT COUNT(*) n FROM conflicts WHERE status='needs_review'`).get();r.json({documents:d.n,processed:d.processed||0,chars:d.chars,facts:f.n,conflicts:c.n,topics:corpusTopics().groups})});
app.get('/api/documents',(q,r)=>r.json(db.prepare('SELECT * FROM documents ORDER BY id DESC').all()));
app.get('/api/facts',(q,r)=>r.json(db.prepare('SELECT f.*,d.original_name FROM facts f JOIN documents d ON d.id=f.document_id ORDER BY f.id DESC LIMIT 500').all()));
app.get('/api/conflicts',(q,r)=>r.json(db.prepare('SELECT * FROM conflicts ORDER BY id DESC').all().map(x=>({...x,details:JSON.parse(x.details),fact_ids:JSON.parse(x.fact_ids)}))));
app.get('/api/search',(q,r)=>r.json(evidence(q.query.q||''))); app.get('/api/topics',(q,r)=>r.json(corpusTopics()));
app.post('/api/documents',upload.array('files',20),async(req,res)=>{const results=[];for(const file of(req.files||[])){const id=db.prepare(`INSERT INTO documents(filename,original_name,mime,size,sha256,status,created_at) VALUES(?,?,?,?,?,?,?)`).run(path.basename(file.path),file.originalname,file.mimetype,file.size,sha256(file.path),'processing',now()).lastInsertRowid;try{const o=await extractFile(file),ins=db.prepare('INSERT INTO document_text(document_id,page,sheet,text) VALUES(?,?,?,?)');const tx=db.transaction(()=>o.pages.forEach(p=>ins.run(id,p.page||null,p.sheet||null,p.text)));tx();extractFacts(id,o.pages);db.prepare('UPDATE documents SET status=?,extracted_chars=?,pages=? WHERE id=?').run(o.total?'processed':'no_text',o.total,o.pages.length,id);results.push({id,filename:file.originalname,status:o.total?'processed':'no_text',chars:o.total,pages:o.pages.length,mode:o.mode})}catch(e){db.prepare('UPDATE documents SET status=? WHERE id=?').run('error',id);results.push({id,filename:file.originalname,status:'error',error:e.message})}finally{fs.rmSync(file.path,{force:true})}}rebuildConflicts();res.json({results})});
app.post('/api/query',async(req,res)=>{const q=clean(req.body?.question);if(!q)return res.status(400).json({error:'Question required'});const facts=answerFacts(q),ev=evidence(q),intent=detectIntent(q);let answer='No matching evidence was found in the local corpus.';if(facts.length){if(intent.compare&&facts.length>=2){const nums=facts.map(f=>({...f,num:normalize(f.value,f.unit)})).filter(f=>f.num!==null);const span=nums.length?`${Math.min(...nums.map(x=>x.num)).toLocaleString()} to ${Math.max(...nums.map(x=>x.num)).toLocaleString()} (normalized units)`:'values vary by source';answer=`Comparison mode found ${facts.length} structured records. ${span}. Review the source rows below before using the result officially.`}else answer=`Found ${facts.length} structured record${facts.length===1?'':'s'} matching the question. Values are extracted from the uploaded corpus and should be source-verified.`}else if(ev.length)answer=`Found ${ev.length} matching source passage${ev.length===1?'':'s'}, but no structured figure matched the requested field.`;const ollama=await localOllama(q,ev.map(e=>`${e.original_name}${e.page?' p.'+e.page:''}: ${e.snippet}`).join('\n'));if(ollama)answer=ollama;res.json({question:q,answer,facts,evidence:ev,intent,grounded:true,provider:ollama?'local Ollama + retrieval':'local retrieval + structured rules',cost:'₹0 API usage by default'})});
app.post('/api/reports',async(req,res)=>{const q=clean(req.body?.question);if(!q)return res.status(400).json({error:'Question required'});const facts=answerFacts(q),ev=evidence(q);const children=[new Paragraph({text:'C-MINE Intelligence — Evidence Report',heading:HeadingLevel.TITLE}),new Paragraph(`Question: ${q}`),new Paragraph(`Generated: ${new Date().toLocaleString()}`),new Paragraph({text:'Executive answer',heading:HeadingLevel.HEADING_2}),new Paragraph(`Retrieved ${facts.length} structured record(s) and ${ev.length} evidence passage(s). This report is grounded only in the local corpus.`),new Paragraph({text:'Structured findings',heading:HeadingLevel.HEADING_2})];if(facts.length)children.push(new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:['Field','Entity','Period','Value','Unit','Source'].map(x=>new TableCell({children:[new Paragraph(x)]}))}),...facts.slice(0,30).map(f=>new TableRow({children:[f.field,f.entity||'—',f.period||'—',f.value||'—',f.unit||'—',`${f.original_name}${f.source_page?' · p.'+f.source_page:''}`].map(x=>new TableCell({children:[new Paragraph(String(x))]}))}))]}));else children.push(new Paragraph('No structured findings were extracted.'));children.push(new Paragraph({text:'Source evidence',heading:HeadingLevel.HEADING_2}));for(const e of ev)children.push(new Paragraph(`• ${e.original_name}${e.page?' · page '+e.page:''}: ${e.snippet}`));const buffer=await Packer.toBuffer(new Document({sections:[{children}]}));const name=`cmine-report-${Date.now()}.docx`,out=path.join(REPORTS,name);fs.writeFileSync(out,buffer);res.download(out,name,()=>fs.rmSync(out,{force:true}))});
app.post('/api/reset',(req,res)=>{db.exec('DELETE FROM conflicts; DELETE FROM facts; DELETE FROM document_text; DELETE FROM documents;');res.json({ok:true})});
app.listen(PORT,()=>console.log(`C-MINE Intelligence running at http://localhost:${PORT}`));
